language: go

services:
  - docker

go:
  - "1.14.x"

env:
  global:
    - HELM_VERSION="v2.16.7"
    - PATH="/tmp:$PATH"

install:
  - wget http://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
  - tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1
  - chmod +x /tmp/helm

before_script:
  - /tmp/helm init --client-only

script:
  - make test-with-integration
